# Generated by Django 4.0.6 on 2022-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about')),
                ('subtitle', models.TextField(blank=True, max_length=10000)),
                ('aboutme', models.TextField(max_length=10000)),
                ('tw_link', models.URLField(blank=True)),
                ('lin_link', models.URLField(blank=True)),
                ('git_link', models.URLField(blank=True)),
            ],
        ),
    ]
