# Generated by Django 4.0.6 on 2022-08-19 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 8, 32, 25, 431820, tzinfo=utc)),
        ),
    ]
